### ISSUE TITLE
我执行错误的，配置好了数据库和搜索

### ISSUE THREAD

**Issue by talway** [keenwon/mongodb-to-elasticsearch#1]
[root@talway mongodb-to-elasticsearch]# pm2 logs
###### ##### Starting streaming logs for [all] process

[import[1]-0 (err)] t Function.Module._load (module.js:280:25)
[import[1]-0 (err)]     at Module.require (module.js:364:17)
[import[1]-0 (err)]     at require (module.js:380:17)
[import[1]-0 (err)]     at Object.<anonymous> (/root/mongodb-to-elasticsearch/import.js:7:21)
[import[1]-0 (err)]     at Module._compile (module.js:456:26)
[import[1]-0 (err)]     at Object.Module._extensions..js (module.js:474:10)
[import[1]-0 (err)]     at Module.load (module.js:356:32)
[import[1]-0 (err)]     at Function.Module._load (module.js:312:12)
[import[1]-0 (err)]     at Function.Module.runMain (module.js:497:10)
[import[1]-0 (err)] module.js:340
[import[1]-0 (err)]     throw err;
[import[1]-0 (err)]           ^
[import[1]-0 (err)] Error: Cannot find module 'elasticsearch'
[import[1]-0 (err)]     at Function.Module._resolveFilename (module.js:338:15)
[import[1]-0 (err)]     at Function.Module._load (module.js:280:25)
[import[1]-0 (err)]     at Module.require (module.js:364:17)
[import[1]-0 (err)]     at require (module.js:380:17)
[import[1]-0 (err)]     at Object.<anonymous> (/root/mongodb-to-elasticsearch/import.js:7:21)
[import[1]-0 (err)]     at Module._compile (module.js:456:26)
[import[1]-0 (err)]     at Object.Module._extensions..js (module.js:474:10)
[import[1]-0 (err)]     at Module.load (module.js:356:32)
[import[1]-0 (err)]     at Function.Module._load (module.js:312:12)
[import[1]-0 (err)]     at Function.Module.runMain (module.js:497:10)
[repair[1]-1 (err)] t Function.Module._load (module.js:280:25)
[repair[1]-1 (err)]     at Module.require (module.js:364:17)
[repair[1]-1 (err)]     at require (module.js:380:17)
[repair[1]-1 (err)]     at Object.<anonymous> (/root/mongodb-to-elasticsearch/repair.js:6:21)
[repair[1]-1 (err)]     at Module._compile (module.js:456:26)
[repair[1]-1 (err)]     at Object.Module._extensions..js (module.js:474:10)
[repair[1]-1 (err)]     at Module.load (module.js:356:32)
[repair[1]-1 (err)]     at Function.Module._load (module.js:312:12)
[repair[1]-1 (err)]     at Function.Module.runMain (module.js:497:10)
[repair[1]-1 (err)] module.js:340
[repair[1]-1 (err)]     throw err;
[repair[1]-1 (err)]           ^
[repair[1]-1 (err)] Error: Cannot find module 'elasticsearch'
[repair[1]-1 (err)]     at Function.Module._resolveFilename (module.js:338:15)
[repair[1]-1 (err)]     at Function.Module._load (module.js:280:25)
[repair[1]-1 (err)]     at Module.require (module.js:364:17)
[repair[1]-1 (err)]     at require (module.js:380:17)
[repair[1]-1 (err)]     at Object.<anonymous> (/root/mongodb-to-elasticsearch/repair.js:6:21)
[repair[1]-1 (err)]     at Module._compile (module.js:456:26)
[repair[1]-1 (err)]     at Object.Module._extensions..js (module.js:474:10)
[repair[1]-1 (err)]     at Module.load (module.js:356:32)
[repair[1]-1 (err)]     at Function.Module._load (module.js:312:12)
[repair[1]-1 (err)]     at Function.Module.runMain (module.js:497:10)

**Comment by talway** [comment]
⌬ PM2 monitoring :

 ● import[1]                           [                              ] errored
[0] [fork_mode]                        [                              ] 0 B   

 ● repair[1]                           [                              ] errored
[1] [fork_mode]                        [                              ] 0 B

**Comment by keenwon** [comment]
这个项目不使用pm2，我更新了readme，你看看。

**Comment by talway** [comment]
我安装你的执行了，提示如下
[root@talway mongodb-to-elasticsearch]# node import.js

##############################################################
#

# !!! MONGOOSE WARNING !!!

#

# This is an UNSTABLE release of Mongoose.

# Unstable releases are available for preview/testing only.

# DO NOT run this in production.

#
##############################################################

Running......
0 0
Elasticsearch ERROR: 2015-04-25T13:28:25Z
  Error: Request error, retrying -- connect ECONNREFUSED
      at Log.error (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:194:18)
      at HttpConnector.<anonymous> (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/connectors/http.js:146:7)
      at ClientRequest.bound (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.emit (events.js:95:17)
      at net.js:440:14
      at process._tickCallback (node.js:419:13)

/root/mongodb-to-elasticsearch/import.js:40
                throw new Error(error);
                      ^
Error: Error: No Living connections
    at /root/mongodb-to-elasticsearch/import.js:40:23
    at respond (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:253:9)
    at sendReqWithConnection (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:173:7)
    at next (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at process._tickCallback (node.js:419:13)

**Comment by talway** [comment]
[root@talway mongodb-to-elasticsearch]# node repair.js

##############################################################
#

# !!! MONGOOSE WARNING !!!

#

# This is an UNSTABLE release of Mongoose.

# Unstable releases are available for preview/testing only.

# DO NOT run this in production.

#
##############################################################

Running......
Tue Oct 28 2014 12:19:34 GMT-0400 (EDT) 0
Elasticsearch ERROR: 2015-04-25T13:30:41Z
  Error: Request error, retrying -- connect ECONNREFUSED
      at Log.error (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:194:18)
      at HttpConnector.<anonymous> (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/connectors/http.js:146:7)
      at ClientRequest.bound (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.emit (events.js:95:17)
      at net.js:440:14
      at process._tickCallback (node.js:419:13)

/root/mongodb-to-elasticsearch/repair.js:46
                throw new Error(error);
                      ^
Error: Error: No Living connections
    at /root/mongodb-to-elasticsearch/repair.js:46:23
    at respond (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:253:9)
    at sendReqWithConnection (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:173:7)
    at next (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at process._tickCallback (node.js:419:13)

**Comment by keenwon** [comment]
看样子是没有连接到Elasticsearch

**Comment by talway** [comment]
config.js 里面的Elasticsearch的端口，你是不是没配置？

**Comment by keenwon** [comment]
格式是ip:port 例如127.0.0.1:9200

**Comment by talway** [comment]
运行一段时间自动错误，是不是内存不足 还是什么原因的；
4624a647f206e663da116f9185494fc46b1e437a 227390
46255a543fa5e98ccbf83ef484766f88ab92bcf8 227400
4626e48f60c54a7ecb49e897b0a435ffe0e42246 227410
Elasticsearch ERROR: 2015-04-25T14:18:19Z
  Error: Request error, retrying -- read ECONNRESET
      at Log.error (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/transport.js:194:18)
      at HttpConnector.<anonymous> (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/src/lib/connectors/http.js:146:7)
      at ClientRequest.bound (/root/mongodb-to-elasticsearch/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.emit (events.js:95:17)
      at net.js:440:14
      at process._tickCallback (node.js:419:13)

**Comment by keenwon** [comment]
好像还是连接不上的问题

**Comment by hu985815621** [comment]
events.js:397
EventEmitter.listenerCount = function(emitter, type) {
                                     ^

RangeError: Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:397:38)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)

我的报这个错误是什么意思？

**Comment by keenwon** [comment]
@hu985815621 其实你只要搜一下`Maximum call stack size exceeded`就知道了，这个小工具写的比较简单，可能错误没有捕获到。

**Comment by hu985815621** [comment]
网上有很多方式，都是要改源码的，我要改你的代码？说实在的  没怎么写过js。。。

**Comment by hu985815621** [comment]
F:\es\mongodb-to-elasticsearch-master>node import.js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND'

js-bson: Failed to load c++ bson extension, using pure JS version

##############################################################
#

# !!! MONGOOSE WARNING !!!

#

# This is an UNSTABLE release of Mongoose.

# Unstable releases are available for preview/testing only.

# DO NOT run this in production.

#
##############################################################
目前是这个错误

**Comment by keenwon** [comment]
``` shell
js-bson: Failed to load c++ bson extension, using pure JS version
```

某个依赖没装好吧，删了node_modules，重新执行npm install

**Comment by hu985815621** [comment]
F:\es\mongodb-to-elasticsearch-master>node import
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version

##############################################################
#

# !!! MONGOOSE WARNING !!!

#

# This is an UNSTABLE release of Mongoose.

# Unstable releases are available for preview/testing only.

# DO NOT run this in production.

#
##############################################################

events.js:397
EventEmitter.listenerCount = function(emitter, type) {
                                     ^

RangeError: Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:397:38)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (F:\es\mongodb-to-elasticsearch-master\node_modules\ela
sticsearch\src\lib\log.js:68:25)

我把第二行 '../build/Release/bson' 改为'bson'，然后这个错误不报错了，但是，下面的RangeError: Maximum call stack size exceeded我不知道怎么解决啊。我不明白为什么会报这个错误。我Mongo里面就一条数据。应该不会溢出吧。

**Comment by ichunhui** [comment]
@talway 遇到了和你一样的问题，请问你是怎么解决的

**Comment by ichunhui** [comment]
@keenwon 你好！请问一下，这个是不是需要额外安装elasticsearch，然后运行./bin/elasticsearch？

**Comment by ichunhui** [comment]
好吧，确实要安装elasticsearch。。
